handlers:
  - url: /favicon.ico
    static_files: favicon.ico
    upload: favicon.ico
runtime: python311
automatic_scaling:
  target_cpu_utilization: 0.92
  max_concurrent_requests: 50
  target_throughput_utilization: 0.7
  max_instances: 1
entrypoint: gunicorn -b 0.0.0.0:8080 app:server