version: '3.8'
services:
  tensorflow:
    build:
      context: .
      network: host
    ports:
      - 8888:8888
    volumes:
      - ./tf-sohail:/tf-sohail
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
          memory: 16G


  
